<?php

use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\Style\Color;
use PhpOffice\PhpPresentation\Style\Alignment;

class PresentationController {

    public function generate() {
        // Create new presentation
        $objPHPPresentation = new PhpPresentation();

        // Set properties
        $objPHPPresentation->getDocumentProperties()->setCreator('Gamma AI')
                                                  ->setLastModifiedBy('Gamma AI')
                                                  ->setTitle('Generated Presentation')
                                                  ->setSubject('Gamma AI Generation')
                                                  ->setDescription('Presentation generated by Gamma AI');

        // Create a slide
        $currentSlide = $objPHPPresentation->getActiveSlide();

        // Add a shape (text)
        $shape = $currentSlide->createRichTextShape()
              ->setHeight(300)
              ->setWidth(600)
              ->setOffsetX(170)
              ->setOffsetY(180);
        $shape->getActiveParagraph()->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        $textRun = $shape->createTextRun('Welcome to Gamma AI Presentation');
        $textRun->getFont()->setBold(true)
                           ->setSize(60)
                           ->setColor(new Color('FF000000'));

        // Add another slide
        $slide2 = $objPHPPresentation->createSlide();
        $shape2 = $slide2->createRichTextShape()
              ->setHeight(300)
              ->setWidth(600)
              ->setOffsetX(170)
              ->setOffsetY(180);
        $shape2->getActiveParagraph()->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        $textRun2 = $shape2->createTextRun('This is the second slide.');
        $textRun2->getFont()->setSize(40)
                            ->setColor(new Color('FF000000'));


        // Save to file
        $oWriter = IOFactory::createWriter($objPHPPresentation, 'PowerPoint2007');

        header('Content-Type: application/vnd.openxmlformats-officedocument.presentationml.presentation');
        header('Content-Disposition: attachment; filename="gamma_presentation.pptx"');
        header('Cache-Control: max-age=0');

        $oWriter->save('php://output');
        exit;
    }
}
